name: kare
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+4

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.5
  shared_preferences: ^2.2.3
  
  # google_mobile_ads: ^5.1.0  
  # riverpod: ^2.5.1
  # flutter_riverpod: ^2.5.1
  # hooks_riverpod: ^2.5.1
  # riverpod_annotation: ^2.6.1
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # build_runner: ^2.4.13
  # riverpod_generator: ^2.4.0
  # riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
 
  assets:
    # - assets/translations/
    - assets/images/